management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
    port: 8081
    compression:
        enabled: true
        min-response-size: 2048
        mime-types: application/json, application/xml, text/html, text/plain
    servlet:
      context-path: /api

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
    name: '@project.name@'
    description: '@project.description@'

http-connector:
  hosts:
    api-catalog:
      host: api-catalog #El cambio en comparación con el archivo application.yml es que aquí se define el nombre del servicio en el archivo hosts
      port: 6070
      endpoints:
        get-city:
          protocol: http
          url: "/api/flights/catalog/city/{code}"
          connectionTimeout: 10000
          readTimeout: 10000
          writeTimeout: 10000

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 5
        sliding-window-type: count_based

        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1

        register-health-indicator: false
        record-excetions:
          - io.netty.handler.timeout.ReadTimeoutException
          - java.lang.RuntimeException
    instances:
        api-catalog:
            baseConfig: default
  ratelimiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 3s
        timeout-duration: 1s
    instances:
      create-reservation:
        baseConfig: default
