management:
  info:
    env:
      enabled: true #Habilita la exposición de información del entorno
  endpoint:
    health:
      show-details: always #Muestra los detalles de la información de salud
  endpoints:
    web:
      base-path: / #Aquí se define el contexto de los endpoints de actuator
      exposure:
        include: '*' #Aquí se definen los endpoints que se expondrán
server:
    port: 8081 #Aquí se define el puerto en el que se ejecutará la aplicación
    compression:
        enabled: true #Habilita la compresión de las respuestas
        min-response-size: 2048 #Aquí se define el tamaño mínimo de la respuesta para que se comprima
        mime-types: application/json, application/xml, text/html, text/plain #Aquí se definen los tipos de contenido que se comprimirán
    servlet:
      context-path: /api #Aquí se define el contexto de la aplicación

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
    name: '@project.name@'
    description: '@project.description@'


